name: Issue assignment
on:
  issues:
    types: [opened]
    
jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1.3.0
              with:
                  assignees: Cedric-Costard,elaes,jpvladlucem,AlexiaMaine
                  numOfAssignee: 2
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
